### ISSUE TITLE
Reproducibility issue

### ISSUE THREAD

**Issue by ismailukman** [LarryUESTC/TMI_GATE#1]
Hi admin and thank you for the excellent work
I wish to reproduce your work for better understanding but I have issues at setup stage.
All requirements.txt installation went fine but `python main.py --train True` shows invalid syntax
Thanks in advance for your response

**Comment by LarryUESTC** [comment]
Thanks, and I will check this.

**Comment by ismailukman** [comment]
Thanks for the prompt response, I will be on standby

**Comment by LarryUESTC** [comment]
Thanks for your patience. Some useless codes and errors (e.g., database codes) have been deleted and fixed.

**Comment by ismailukman** [comment]
Thanks again for the support, I am still unable to get around the issue...  
![Screenshot-gnn-ssl-error](https://user-images.githubusercontent.com/8543691/201914888-9c920532-8d52-4b64-85d6-48c2bd47a800.png)

**Comment by LarryUESTC** [comment]
Ori_ABIDE_MA.npy
<https://drive.google.com/file/d/10z7ELmHvWhvTa1kZF7kod8cnIFJun1eZ/view?usp=drive_web>
 Ori_ABIDE_SA.npy
<https://drive.google.com/file/d/1xy62lG5Keasj1vRRlckuIiuFpOmlKA_V/view?usp=drive_web>
The data are uploaded on BaiduYun drive (see Sec. Preparation at README.md
which I updated yesterday).
For convenience, I upload the data on google drive (see attachment)

ismailukman ***@***.***> 于2022年11月15日周二 20:02写道：

**Comment by ismailukman** [comment]
Thanks again @LarryUESTC,
I will surely keep you posted (pls, I need access on the shared drive)

**Comment by LarryUESTC** [comment]
Thank you!

ismailukman ***@***.***> 于2022年11月16日周三 22:53写道：

**Comment by LarryUESTC** [comment]
sorry for opening access, now it can be downloaded

**Comment by LarryUESTC** [comment]
down

**Comment by ismailukman** [comment]
Thanks lot... The issue has been resolved with `Ori_ABIDE_SA` dataset
