### ISSUE TITLE
The construction of 'subject_IDs.txt' file

### ISSUE THREAD

**Issue by justwqq** [LarryUESTC/TMI_GATE#2]
Hello, I try to generate your own data using Pre_time_MA.py and Pre_time_SA.py.
Specifically, I downloaded ABIDE dataset,  but, I am not sure about the specific format of subject_IDs.txt. 
Could you please give me more details?

**Comment by LarryUESTC** [comment]
I apologize for the delayed response. I have been quite busy recently, but I will make it a priority to review your question as soon as possible.

**Comment by LarryUESTC** [comment]
Sorry for delayed response T-T, Here is ``subject_IDs"~
[subject_IDs.txt](https://github.com/LarryUESTC/GATE/files/13691164/subject_IDs.txt)
